import { BasicModel } from '/@/api/model/baseModel';

/**
 * 导入临时表
 */
export interface SysImportExcelTemporary extends BasicModel {
  // 模板id
  templateId?: string;
  // 导入用户id
  userId?: string;
  // 验证结果
  verificationStatus?: string;
  // 错误信息
  verificationResults?: string;
  // 导入字段
  field1?: string;
  // 导入字段
  field2?: string;
  // 导入字段
  field3?: string;
  // 导入字段
  field4?: string;
  // 导入字段
  field5?: string;
  // 导入字段
  field6?: string;
  // 导入字段
  field7?: string;
  // 导入字段
  field8?: string;
  // 导入字段
  field9?: string;
  // 导入字段
  field10?: string;
  // 导入字段
  field11?: string;
  // 导入字段
  field12?: string;
  // 导入字段
  field13?: string;
  // 导入字段
  field14?: string;
  // 导入字段
  field15?: string;
  // 导入字段
  field16?: string;
  // 导入字段
  field17?: string;
  // 导入字段
  field18?: string;
  // 导入字段
  field19?: string;
  // 导入字段
  field20?: string;
  // 导入字段
  field21?: string;
  // 导入字段
  field22?: string;
  // 导入字段
  field23?: string;
  // 导入字段
  field24?: string;
  // 导入字段
  field25?: string;
  // 导入字段
  field26?: string;
  // 导入字段
  field27?: string;
  // 导入字段
  field28?: string;
  // 导入字段
  field29?: string;
  // 导入字段
  field30?: string;
  // 导入字段
  field31?: string;
  // 导入字段
  field32?: string;
  // 导入字段
  field33?: string;
  // 导入字段
  field34?: string;
  // 导入字段
  field35?: string;
  // 导入字段
  field36?: string;
  // 导入字段
  field37?: string;
  // 导入字段
  field38?: string;
  // 导入字段
  field39?: string;
  // 导入字段
  field40?: string;
  // 导入字段
  field41?: string;
  // 导入字段
  field42?: string;
  // 导入字段
  field43?: string;
  // 导入字段
  field44?: string;
  // 导入字段
  field45?: string;
  // 导入字段
  field46?: string;
  // 导入字段
  field47?: string;
  // 导入字段
  field48?: string;
  // 导入字段
  field49?: string;
  // 导入字段
  field50?: string;
}
